### PR TITLE
Adding Sorting Algorithms in Python

### PR DESCRIPTION
**Pull request by Aravindhsiva**
Thanks in advance for merging my contributions 😀

### CODE REVIEW

**Comment by Aravindhsiva** [comment]
Can anyone pls review and merge my contribution ?

**Comment by PeanutCoffee** [comment]
Create an issue for the same please.

**Comment by Aravindhsiva** [comment]
@PeanutCoffee Created an issue !!

**Comment by PeanutCoffee** [comment]
👍

**Pull request merged**
