### PR TITLE
fixes #44

### LINKED ISSUE #44: Help with the CONTRIBUTING.md file
Can someone Help with the CONTRIBUTING.md and add the contributors

### PR DESCRIPTION
**Pull request by dasShounak**
Added contributing guidelines and contributors list to the CONTRIBUTING.md file.

### CODE REVIEW

**Comment by PeanutCoffee** [comment]
Try adding the contributor's name with their github profile link.

**Comment by dasShounak** [comment]
Sure. I'll do the changes

**Comment by dasShounak** [comment]
Is it ok?

**Review by PeanutCoffee — APPROVED** [review]
Looks good,

**Comment by PeanutCoffee** [comment]
> Is it ok?

There was some issue while merging, so I removed a few lines. Looks good now. I have merged the pr.

**Pull request merged**
